name: KarimAllah Ahmed - Random Thoughts
author: KarimAllah Ahmed
domain: karimallah.github.io
baseurl:
description:
github: http://www.github.com/KarimAllah/karimallah.github.io
twitter: http://www.twitter.com/KarimAllah
facebook: https://www.facebook.com/karim.allah.ahmed
linkedin: https://www.linkedin.com/in/karimallah/
logo: /images/logo-hq.png
icon: /images/mstile-310x310.png
email: karim.allah.ahmed@gmail.com
location: $HOME
disqus: karimallahahmed
permalink: /:categories/:title.html
##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  -
   scope:
      path: ""
      type: "pages"
   values:
      layout: "default"
  -
   scope:
      path: ""
      type: "posts"
   values:
      layout: "post"